export type IconPropsType = {
  width?: number;
  height?: number;
  color?: string;
};

export * from "./arrow-right";
export * from "./arrow-left";
export * from "./close";
export * from "./menu";
export * from "./caret-down";
export * from "./instagram";
export * from "./facebook";
export * from "./arrow-circle-up-right";
export * from "./person";
export * from "./partner";
export * from "./volunteer";
export * from "./thank-you-illustration";
export * from "./search";
export * from "./chevronlefticon";
export * from "./chevronrighticon";
export * from "./facebook-colored";
export * from "./instagram-colored";
export * from "./x-colored";
export * from "./gmail-colored";
export * from "./verified";
export * from "./volunteering";
export * from "./events";
export * from "./charity";
export * from "./fundraising";
export * from "./phone";
export * from "./mail";
